### ISSUE TITLE
Can't not get EasyJS.retValue

### ISSUE THREAD

**Issue by feijiwa** [zkrige/EasyJSWKWebView#1]
after code:

        var argStr = (formattedArgs.length > 0 ? ":" + encodeURIComponent(formattedArgs.join(":")) : "");
        window.webkit.messageHandlers.Listener.postMessage(obj + ":" + encodeURIComponent(functionName) + argStr);
        var ret = EasyJS.retValue;
        EasyJS.retValue = undefined;

ret is always undefined, EasyJS.retValue is setted Asynchronous.

**Comment by zkrige** [comment]
will investigate shortly

**Comment by zkrige** [comment]
have added detailed sample showing how to get value back from ios - https://github.com/zkrige/EasyJSWKWebView/commit/d3d07d4bc850c3d1b60c0991e470f269a5a2b8c1

fyi, I have also added callback function parameters. see sample code

**Comment by feijiwa** [comment]
Thanks for your response.

        function test() {
            var value = JSInterface.test();
            console.log("returned value : " + value);
        }

I want to fit my old web project with usage like this(Get return value Synchronous).

I tested, but the value is undefined.
