### ISSUE TITLE
Can't not get return value Synchronous.

### ISSUE THREAD

**Issue by feijiwa** [zkrige/EasyJSWKWebView#2]
Thanks for your response.

    function test() {
        var value = JSInterface.test();
        console.log("returned value : " + value);
    }
I want to fit my old web project with usage like this(Get return value Synchronous).

I tested, but the value is undefined.

**Comment by zkrige** [comment]
I've been fiddling with this for a while now, and I dont think its possible to get the value syncronous in using a WKWebView.

One of the main differences between UIWebView and WKWebView is that WKWebView doesn't allow you to run javascript synchronous.

You're going to have to go with a callback for the return value.
