### ISSUE TITLE
Need this code in swift

### ISSUE THREAD

**Issue by chinmaykdas** [zkrige/EasyJSWKWebView#3]
Please convert this code to swift 3. We need this code swift. I was trying to convert this to swift but there is an NSInvocation used which I could not convert to swift.

**Comment by zkrige** [comment]
This code can't be converted to swift precisely because of the `NSInvocation`

The best you can do is have an objc-bridge back to this code

**Comment by chinmaykdas** [comment]
Yes, I have been trying another way out for the `NSInvocation` but unfortunately could not convert it. Please update me If you found a better way out in swift. It is a really nice library and this works with the bridging header. Thank you.

**Comment by zkrige** [comment]
If I can ever figure out how to get rid of `NSInvocation` then I will post an update here immediately
