### ISSUE TITLE
iOS 13 : iPad. After 1st time Web view loading , it is not calling -(void)webView:(WKWebView *)webView didCommitNavigation:(WKNavigation *)navigation{} method again

### ISSUE THREAD

**Issue by NandParikh** [zkrige/EasyJSWKWebView#6]
iOS 13 : iPad. After 1st time Web view loading , it is not calling -(void)webView:(WKWebView *)webView didCommitNavigation:(WKNavigation *)navigation{} method again

**Comment by zkrige** [comment]
Have you got a sample app I can test with?

Thats a webview delegate method and doesn't really have anything to do with the JSBridge

**Comment by NandParikh** [comment]
> Have you got a sample app I can test with?
> 
> Thats a webview delegate method and doesn't really have anything to do with the JSBridge

As it is in one of my project so, I can't share it. it is working fine in (iOS 12) and also working fine in iPhone (iOS 13). but not working in iPad with (iOS 13)

**Comment by NandParikh** [comment]
It is solved. it was Agent problem in code. Thanks for your support!!!!.

**Comment by zkrige** [comment]
ah perfect - thank you for letting me know
